import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#ffffff' },
  searchRow: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 8 },
  searchPill: {
    backgroundColor: '#ffffff',
    borderRadius: 9999,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 8,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  searchInput: { flex: 1, color: '#0b2135' },
  addrRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingBottom: 12, gap: 8 },
  muted: { color: '#6c757d' },
  addrButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#ffffff', borderRadius: 9999, paddingHorizontal: 10, paddingVertical: 6, gap: 6 },
  addrButtonText: { color: '#0b2135', fontWeight: '600' },
  filterButton: { marginLeft: 'auto', backgroundColor: '#ffffff', borderRadius: 9999, paddingHorizontal: 10, paddingVertical: 6 },
  section: { marginBottom: 12 },
  sectionHeader: { paddingHorizontal: 16, marginVertical: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sectionTitle: { color: '#0b2135', fontSize: 18, fontWeight: '700' },
  linkPrimary: { color: '#0d6efd' },
  catCircle: { width: 72, alignItems: 'center', gap: 6 },
  catText: { color: '#0b2135', fontSize: 12 },
  banner: { width: 280, height: 140, borderRadius: 16, overflow: 'hidden', backgroundColor: '#e9ecef' },
  bannerImg: { width: '100%', height: '100%' },
  bannerBadge: { position: 'absolute', top: 8, left: 8, backgroundColor: '#ffffff', borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4 },
  badgeText: { color: '#0b2135', fontWeight: '700', fontSize: 12 },
  coupon: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#ffffff', borderWidth: 1, borderStyle: 'dashed', borderColor: '#0d6efd', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, gap: 6 },
  couponText: { color: '#0d6efd', fontWeight: '700' },
  couponSmall: { color: '#0b2135' },
  cards: { paddingHorizontal: 16, gap: 12 },
  card: { backgroundColor: '#ffffff', borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: '#e9ecef' },
  cardImg: { width: '100%', height: 140 },
  cardBody: { padding: 12, gap: 6 },
  cardTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  cardTitle: { color: '#0b2135', fontWeight: '700', fontSize: 16, flex: 1 },
  badge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#fff3cd', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 999 },
  rateText: { color: '#664d03', fontWeight: '700', fontSize: 12 },
  cardMuted: { color: '#6c757d' },
});

export default styles;
